sudo: required
services:
  - docker

before_install:
  - docker build -t abeego/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run abeego/react-test npm test -- --coverage

after_success:
  - docker build -t abeego/complex-client ./client
  - docker build -t abeego/complex-nginx ./nginx
  - docker build -t abeego/complex-api ./api
  - docker build -t abeego/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abeego/complex-client
  - docker push abeego/complex-nginx
  - docker push abeego/complex-api
  - docker push abeego/complex-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: complex
  env: Complex-env
  bucket_name: elasticbeanstalk-eu-central-1-486418823754
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
